/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.57 from the
 * contents of UUID.xs. Do not edit this file, edit UUID.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "lib/UUID.xs"
#ifdef __cplusplus
extern "C" {
#endif

/*
**  It seems that perfection is attained
**  not when there is nothing more to add,
**  but when there is nothing more to remove.
**                -- Antoine de Saint Exupery
*/

#define NO_XSLOCKS
#include "ulib/UUID.h"
#include "XSUB.h"
#include "ulib/chacha.h"
#include "ulib/clock.h"
#include "ulib/compare.h"
#include "ulib/gen.h"
#include "ulib/gettime.h"
#include "ulib/hash.h"
#include "ulib/pack.h"
#include "ulib/parse.h"
#include "ulib/splitmix.h"
#include "ulib/util.h"
#include "ulib/xoshiro.h"

#ifdef __cplusplus
}
#endif

/* 2 hex digits per byte + 4 separators */
#define UUID_BUFFSZ 36


#define MY_CXT_KEY "UUID::_guts" XS_VERSION
/* my_cxt_t global typedef lives in TYPE.h */
START_MY_CXT


#ifdef PERL_IMPLICIT_CONTEXT
# define dUCXT     dMY_CXT
# define UCXT_INIT MY_CXT_INIT
#else
# define dUCXT     my_cxt_t *my_cxtp = &my_cxt;
# define UCXT_INIT my_cxt_t *my_cxtp = &my_cxt;
#endif

#define UU_GEN_TMPL(ver, out, su, dptr)   \
    SV_CHECK_THINKFIRST_COW_DROP(out);    \
    if (isGV_with_GP(out))                \
        croak("%s", PL_no_modify);        \
    SvUPGRADE(out, SVt_PV);               \
    UMTX_LOCK {                           \
    uu_gen_v##ver(aUCXT, &su, dptr);      \
    } UMTX_UNLOCK                         \
    dptr = SvGROW(out, sizeof(uu_t)+1);   \
    uu_pack_v##ver(&su, (U8*)dptr);       \
    dptr[sizeof(uu_t)] = '\0';            \
    SvCUR_set(out, sizeof(uu_t));         \
    (void)SvPOK_only(out);                \
    if (SvTYPE(out) == SVt_PVCV)          \
        CvAUTOLOAD_off(out);

#define UU_ALIAS_GEN_V0(out, su, dptr) UU_GEN_TMPL(0, out, su, dptr)
#define UU_ALIAS_GEN_V1(out, su, dptr) UU_GEN_TMPL(1, out, su, dptr)
#define UU_ALIAS_GEN_V3(out, su, dptr) UU_GEN_TMPL(3, out, su, dptr)
#define UU_ALIAS_GEN_V4(out, su, dptr) UU_GEN_TMPL(4, out, su, dptr)
#define UU_ALIAS_GEN_V5(out, su, dptr) UU_GEN_TMPL(5, out, su, dptr)
#define UU_ALIAS_GEN_V6(out, su, dptr) UU_GEN_TMPL(6, out, su, dptr)
#define UU_ALIAS_GEN_V7(out, su, dptr) UU_GEN_TMPL(7, out, su, dptr)


#define UU_UNPARSE_TMPL(case, in, out, su, dptr)  \
    if (SvPOK(in)) {                               \
        dptr = SvGROW(in, sizeof(uu_t));            \
        uu_pack_unpack((unsigned char*)dptr, &su);   \
        SV_CHECK_THINKFIRST_COW_DROP(out);            \
        if (isGV_with_GP(out))                        \
            croak("%s", PL_no_modify);                \
        SvUPGRADE(out, SVt_PV);                       \
        SvPOK_only(out);                              \
        dptr = SvGROW(out, UUID_BUFFSZ+1);            \
        uu_parse_unparse_ ## case ## er1(&su, dptr);  \
        dptr[UUID_BUFFSZ] = '\0';                     \
        SvCUR_set(out, UUID_BUFFSZ);                 \
        (void)SvPOK_only(out);                      \
        if (SvTYPE(out) == SVt_PVCV)               \
            CvAUTOLOAD_off(out);                  \
    }

#define UU_ALIAS_UNPARSE_LOWER(in, out, su, dptr) UU_UNPARSE_TMPL(low, in, out, su, dptr)
#define UU_ALIAS_UNPARSE_UPPER(in, out, su, dptr) UU_UNPARSE_TMPL(upp, in, out, su, dptr)


#define UU_UUID_TMPL(ver, su, dptr)  \
    UMTX_LOCK {                       \
    uu_gen_v##ver(aUCXT, &su, dptr);   \
    } UMTX_UNLOCK                       \
    RETVAL = newSV(UUID_BUFFSZ+1);       \
    dptr = SvPVX(RETVAL);                \
    uu_parse_unparse_v##ver(&su, dptr);  \
    dptr[UUID_BUFFSZ] = '\0';            \
    SvCUR_set(RETVAL, UUID_BUFFSZ);     \
    SvPOK_only(RETVAL);

#define UU_ALIAS_UUID0(su, dptr) UU_UUID_TMPL(0, su, dptr)
#define UU_ALIAS_UUID1(su, dptr) UU_UUID_TMPL(1, su, dptr)
#define UU_ALIAS_UUID3(su, dptr) UU_UUID_TMPL(3, su, dptr)
#define UU_ALIAS_UUID4(su, dptr) UU_UUID_TMPL(4, su, dptr)
#define UU_ALIAS_UUID5(su, dptr) UU_UUID_TMPL(5, su, dptr)
#define UU_ALIAS_UUID6(su, dptr) UU_UUID_TMPL(6, su, dptr)
#define UU_ALIAS_UUID7(su, dptr) UU_UUID_TMPL(7, su, dptr)


#define UU_ALIAS_VERSION(in, su, str, len)       \
    RETVAL = -1;                                  \
    if (SvPOK(in)) {                               \
        str = SvPV(in, len);                        \
        if (len == sizeof(uu_t)) {                   \
            uu_pack_unpack((unsigned char*)str, &su); \
            RETVAL = uu_type(&su);                    \
        }                                            \
    }

const struct_uu_t UU_namespace_dns  = {{ 0x6ba7b810, 0x9dad, 0x11d1, 0x80b4, {0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8}}};
const struct_uu_t UU_namespace_url  = {{ 0x6ba7b811, 0x9dad, 0x11d1, 0x80b4, {0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8}}};
const struct_uu_t UU_namespace_oid  = {{ 0x6ba7b812, 0x9dad, 0x11d1, 0x80b4, {0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8}}};
const struct_uu_t UU_namespace_x500 = {{ 0x6ba7b814, 0x9dad, 0x11d1, 0x80b4, {0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8}}};

static void smem_init(pUCXT) {
#if defined(USE_WIN32_NATIVE) || defined(USE_WIN32_ALIEN)
    IV size = sizeof(shared_mem_t);
    SMEM = VirtualAlloc(NULL, size, MEM_COMMIT|MEM_RESERVE, PAGE_READWRITE);
    if (!SMEM) croak("VirtualAlloc: %li\n", GetLastError());
    UCXT.shared_len = size;
#else
    IV pagesz = sysconf(_SC_PAGESIZE);
    IV npages = sizeof(shared_mem_t) / pagesz;
    if (sizeof(shared_mem_t) % pagesz) ++npages;
    IV nbytes = npages * pagesz;
    SMEM = (shared_mem_t*)mmap(NULL, nbytes, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0);
    if (SMEM == MAP_FAILED) croak("mmap: %s\n", strerror((IV)SMEM));
    UCXT.shared_len = nbytes;
#endif
}


#line 158 "lib/UUID.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

/* simple backcompat versions of the TARGx() macros with no optimisation */
#ifndef TARGi
#  define TARGi(iv, do_taint) sv_setiv_mg(TARG, iv)
#  define TARGu(uv, do_taint) sv_setuv_mg(TARG, uv)
#  define TARGn(nv, do_taint) sv_setnv_mg(TARG, nv)
#endif

#line 309 "lib/UUID.c"

XS_EUPXS(XS_UUID__hide_always); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID__hide_always)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 172 "lib/UUID.xs"
        dUCXT;
#line 322 "lib/UUID.c"
#line 174 "lib/UUID.xs"
        UMTX_LOCK {
        uu_gen_setuniq(aUCXT);
        } UMTX_UNLOCK
#line 327 "lib/UUID.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_UUID__hide_mac); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID__hide_mac)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 182 "lib/UUID.xs"
        dUCXT;
#line 345 "lib/UUID.c"
#line 184 "lib/UUID.xs"
        UMTX_LOCK {
        uu_gen_setrand(aUCXT);
        } UMTX_UNLOCK
#line 350 "lib/UUID.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_UUID__persist); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID__persist)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
#line 192 "lib/UUID.xs"
        dUCXT;
#line 366 "lib/UUID.c"
	SV *	RETVAL;
#line 194 "lib/UUID.xs"
        char                *ptr;
        SV                  *sv;
        persist_t           persist;
#line 372 "lib/UUID.c"
#line 198 "lib/UUID.xs"
        if (items > 1)
            croak("Usage: _persist([path/to/file])");
        if (items == 0) {
            UMTX_LOCK {
            uu_clock_getpath(aUCXT, &persist);
            } UMTX_UNLOCK
            if (persist.len)
                RETVAL = newSVpvn((char*)persist.path, persist.len);
            else
                RETVAL = newSV(0);
        }
        else { /* items == 1 */
            Zero(&persist, 1, persist_t);
            if (SvTRUE(ST(0))) {
                sv = ST(0);
                ptr = SvPV(sv, persist.len);

                if (persist.len > MAX_PERSIST_LEN)
                    croak("Persist path too long. (max %" UVuf ")", (UV)MAX_PERSIST_LEN);  /* XXX croak() or croak_caller() ? */

                /* includes null */
                Copy(ptr, persist.path, persist.len+1, UCHAR);

                UMTX_LOCK {
                uu_clock_setpath(aUCXT, &persist);
                } UMTX_UNLOCK
            }
            else {
                UMTX_LOCK {
                uu_clock_setpath(aUCXT, &persist);
                } UMTX_UNLOCK
            }
            RETVAL = &PL_sv_yes;
        }
#line 408 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID__realnode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID__realnode)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 239 "lib/UUID.xs"
        dUCXT;
#line 425 "lib/UUID.c"
	SV *	RETVAL;
#line 241 "lib/UUID.xs"
        int             rv;
        char            *dptr;
        struct_uu_t     su;
#line 431 "lib/UUID.c"
#line 245 "lib/UUID.xs"
        UMTX_LOCK {
        rv = uu_gen_realnode(aUCXT, &su);
        } UMTX_UNLOCK
        if (rv) {
            RETVAL = newSV(UUID_BUFFSZ+1);
            dptr = SvPVX(RETVAL);
            uu_parse_unparse_v0(&su, dptr);
            dptr[UUID_BUFFSZ] = '\0';
            SvCUR_set(RETVAL, UUID_BUFFSZ);
            SvPOK_only(RETVAL);
        }
        else
            RETVAL = &PL_sv_no;
#line 446 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID__defer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID__defer)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
#line 265 "lib/UUID.xs"
        dUCXT;
#line 463 "lib/UUID.c"
	SV *	RETVAL;
#line 267 "lib/UUID.xs"
        SV *duration;
#line 467 "lib/UUID.c"
#line 269 "lib/UUID.xs"
        if (items == 0) {
            RETVAL = newSVnv(SMEM->clock_defer_100ns / 10000000.0);
        }
        else if (items == 1) {
            duration = ST(0);
            if (!looks_like_number(duration))
                croak_caller("Non-numeric :defer argument");
            UMTX_LOCK {
            SMEM->clock_defer_100ns = (U64)(SvNV(duration) * 10000000.0);
            } UMTX_UNLOCK
            RETVAL = &PL_sv_yes;
        }
        else
            croak("Too many arguments for _defer()");
#line 483 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_clear); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_clear)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "io");
    {
	SV *	io = ST(0)
;
#line 291 "lib/UUID.xs"
        dUCXT;
#line 502 "lib/UUID.c"
#line 293 "lib/UUID.xs"
        struct_uu_t     su;
        char            *dptr = NULL;
#line 506 "lib/UUID.c"
#line 296 "lib/UUID.xs"
        UU_ALIAS_GEN_V0(io, su, dptr);
#line 509 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_compare); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_compare)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "in1, in2");
    {
	SV *	in1 = ST(0)
;
	SV *	in2 = ST(1)
;
#line 304 "lib/UUID.xs"
        dUCXT;
#line 528 "lib/UUID.c"
	IV	RETVAL;
	dXSTARG;
#line 306 "lib/UUID.xs"
        STRLEN  len1, len2;
#line 533 "lib/UUID.c"
#line 308 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        if (SvPOK(in1) && SvPOK(in2)
            && SvCUR(in1) == sizeof(uu_t)
            && SvCUR(in2) == sizeof(uu_t))
            RETVAL = uu_compare_binary(
                (U8*)SvPV_force(in1, len1),
                (U8*)SvPV_force(in2, len2)
            );
        else if (!SvOK(in1))
            RETVAL = SvOK(in2) ? -1 : 0;
        else if (!SvOK(in2))
            RETVAL = 1;
        else
            RETVAL = sv_cmp(in1, in2);
#line 549 "lib/UUID.c"
	TARGi((IV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_copy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_copy)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "out, in");
    {
	SV *	out = ST(0)
;
	SV *	in = ST(1)
;
#line 331 "lib/UUID.xs"
        dUCXT;
#line 570 "lib/UUID.c"
#line 333 "lib/UUID.xs"
        struct_uu_t     su;
        STRLEN          len;
        char            *dptr;
#line 575 "lib/UUID.c"
#line 337 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        if (!SvPOK(in) || SvCUR(in) != sizeof(uu_t))
            uu_clear(&su);
        else
            uu_pack_unpack((U8*)SvPV_force(in, len), &su);
        SV_CHECK_THINKFIRST_COW_DROP(out);
        if (isGV_with_GP(out))
            croak("%s", PL_no_modify);
        SvUPGRADE(out, SVt_PV);
        dptr = SvGROW(out, sizeof(uu_t)+1);
        uu_pack_v1(&su, (U8*)dptr);
        dptr[sizeof(uu_t)] = '\0';
        SvCUR_set(out, sizeof(uu_t));
        (void)SvPOK_only(out);
        if (SvTYPE(out) == SVt_PVCV)
            CvAUTOLOAD_off(out);
#line 593 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "out");
    {
	SV *	out = ST(0)
;
#line 359 "lib/UUID.xs"
        dUCXT;
#line 610 "lib/UUID.c"
#line 361 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 614 "lib/UUID.c"
#line 364 "lib/UUID.xs"
        UU_ALIAS_GEN_V4(out, su, dptr);
#line 617 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_random); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_random)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "out");
    {
	SV *	out = ST(0)
;
#line 371 "lib/UUID.xs"
        dUCXT;
#line 634 "lib/UUID.c"
#line 373 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 638 "lib/UUID.c"
#line 376 "lib/UUID.xs"
        UU_ALIAS_GEN_V4(out, su, dptr);
#line 641 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_time); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_time)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "out");
    {
	SV *	out = ST(0)
;
#line 383 "lib/UUID.xs"
        dUCXT;
#line 658 "lib/UUID.c"
#line 385 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 662 "lib/UUID.c"
#line 388 "lib/UUID.xs"
        UU_ALIAS_GEN_V1(out, su, dptr);
#line 665 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_v0); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_v0)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "out");
    {
	SV *	out = ST(0)
;
#line 395 "lib/UUID.xs"
        dUCXT;
#line 682 "lib/UUID.c"
#line 397 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 686 "lib/UUID.c"
#line 400 "lib/UUID.xs"
        UU_ALIAS_GEN_V0(out, su, dptr);
#line 689 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_v1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_v1)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "out");
    {
	SV *	out = ST(0)
;
#line 407 "lib/UUID.xs"
        dUCXT;
#line 706 "lib/UUID.c"
#line 409 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 710 "lib/UUID.c"
#line 412 "lib/UUID.xs"
        UU_ALIAS_GEN_V1(out, su, dptr);
#line 713 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_v3); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_v3)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "out, namespace, name");
    {
	SV *	out = ST(0)
;
	SV *	namespace = ST(1)
;
	SV *	name = ST(2)
;
#line 421 "lib/UUID.xs"
        dUCXT;
#line 734 "lib/UUID.c"
#line 423 "lib/UUID.xs"
        char            *dptr, *sptr;
        STRLEN          dlen, slen;
        struct_uu_t     su;
#line 739 "lib/UUID.c"
#line 427 "lib/UUID.xs"
        SvUPGRADE(namespace, SVt_PV);
        SvUPGRADE(name,      SVt_PV);
        sptr = SvPV(namespace, slen);
        dptr = SvPV(name,      dlen);

        if (slen == 36 && !uu_parse(sptr, &su)) {
            /* uuid string */
            UU_ALIAS_GEN_V3(out, su, dptr);
        }
        else if (slen == 16) {
            /* assume binary uuid */
            uu_pack_unpack((unsigned char*)sptr, &su);
            UU_ALIAS_GEN_V3(out, su, dptr);
        }
        else if (slen > 0  /* ibcmp first appears in v5.7.3 */
            && ( (slen == 3 && !ibcmp(sptr, "dns",  (I32)slen) && CopyD(&UU_namespace_dns,  &su, 1, struct_uu_t))
              || (slen == 3 && !ibcmp(sptr, "url",  (I32)slen) && CopyD(&UU_namespace_url,  &su, 1, struct_uu_t))
              || (slen == 3 && !ibcmp(sptr, "oid",  (I32)slen) && CopyD(&UU_namespace_oid,  &su, 1, struct_uu_t))
              || (slen == 4 && !ibcmp(sptr, "x500", (I32)slen) && CopyD(&UU_namespace_x500, &su, 1, struct_uu_t))
            )
        ) {
            UU_ALIAS_GEN_V3(out, su, dptr);
        }
        else {  /* slen == 0 ; assume url type */
            CopyD(&UU_namespace_url, &su, 1, struct_uu_t);
            UU_ALIAS_GEN_V3(out, su, dptr);
        }
#line 768 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_v4); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_v4)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "out");
    {
	SV *	out = ST(0)
;
#line 460 "lib/UUID.xs"
        dUCXT;
#line 785 "lib/UUID.c"
#line 462 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 789 "lib/UUID.c"
#line 465 "lib/UUID.xs"
        UU_ALIAS_GEN_V4(out, su, dptr);
#line 792 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_v5); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_v5)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "out, namespace, name");
    {
	SV *	out = ST(0)
;
	SV *	namespace = ST(1)
;
	SV *	name = ST(2)
;
#line 474 "lib/UUID.xs"
        dUCXT;
#line 813 "lib/UUID.c"
#line 476 "lib/UUID.xs"
        char            *dptr, *sptr;
        STRLEN          dlen, slen;
        struct_uu_t     su;
#line 818 "lib/UUID.c"
#line 480 "lib/UUID.xs"
        SvUPGRADE(namespace, SVt_PV);
        SvUPGRADE(name,      SVt_PV);
        sptr = SvPV(namespace, slen);
        dptr = SvPV(name,      dlen);

        if (slen == 36 && !uu_parse(sptr, &su)) {
            /* uuid string */
            UU_ALIAS_GEN_V5(out, su, dptr);
        }
        else if (slen == 16) {
            /* assume binary uuid */
            uu_pack_unpack((unsigned char*)sptr, &su);
            UU_ALIAS_GEN_V5(out, su, dptr);
        }
        else if (slen > 0  /* ibcmp first appears in v5.7.3 */
            && ( (slen == 3 && !ibcmp(sptr, "dns",  (I32)slen) && CopyD(&UU_namespace_dns,  &su, 1, struct_uu_t))
              || (slen == 3 && !ibcmp(sptr, "url",  (I32)slen) && CopyD(&UU_namespace_url,  &su, 1, struct_uu_t))
              || (slen == 3 && !ibcmp(sptr, "oid",  (I32)slen) && CopyD(&UU_namespace_oid,  &su, 1, struct_uu_t))
              || (slen == 4 && !ibcmp(sptr, "x500", (I32)slen) && CopyD(&UU_namespace_x500, &su, 1, struct_uu_t))
            )
        ) {
            UU_ALIAS_GEN_V5(out, su, dptr);
        }
        else {  /* slen == 0 ; assume url type */
            CopyD(&UU_namespace_url, &su, 1, struct_uu_t);
            UU_ALIAS_GEN_V5(out, su, dptr);
        }
#line 847 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_v6); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_v6)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "out");
    {
	SV *	out = ST(0)
;
#line 513 "lib/UUID.xs"
        dUCXT;
#line 864 "lib/UUID.c"
#line 515 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 868 "lib/UUID.c"
#line 518 "lib/UUID.xs"
        UU_ALIAS_GEN_V6(out, su, dptr);
#line 871 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_generate_v7); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_generate_v7)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "out");
    {
	SV *	out = ST(0)
;
#line 525 "lib/UUID.xs"
        dUCXT;
#line 888 "lib/UUID.c"
#line 527 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 892 "lib/UUID.c"
#line 530 "lib/UUID.xs"
        UU_ALIAS_GEN_V7(out, su, dptr);
#line 895 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_is_null); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_is_null)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "in");
    {
	SV *	in = ST(0)
;
#line 537 "lib/UUID.xs"
        dUCXT;
#line 912 "lib/UUID.c"
	IV	RETVAL;
	dXSTARG;
#line 539 "lib/UUID.xs"
        STRLEN  len;
#line 917 "lib/UUID.c"
#line 541 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        if (!SvPOK(in))
            RETVAL = 0;
        else if (SvCUR(in) != sizeof(uu_t))
            RETVAL = 0;
        else
            RETVAL = uu_compare_isnull_binary((U8*)SvPV(in, len));
#line 926 "lib/UUID.c"
	TARGi((IV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_parse); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_parse)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "in, out");
    {
	SV *	in = ST(0)
;
	SV *	out = ST(1)
;
#line 557 "lib/UUID.xs"
        dUCXT;
#line 947 "lib/UUID.c"
	IV	RETVAL;
	dXSTARG;
#line 559 "lib/UUID.xs"
        char            *dptr;
        struct_uu_t     su;
#line 953 "lib/UUID.c"
#line 562 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        /* XXX might see uninitialized data */
        RETVAL = -1;
        if (SvPOK(in) && !uu_parse(SvGROW(in, UUID_BUFFSZ+1), &su)) {
            SV_CHECK_THINKFIRST_COW_DROP(out);
            if (isGV_with_GP(out))
                croak("%s", PL_no_modify);
            SvUPGRADE(out, SVt_PV);
            dptr = SvGROW(out, sizeof(uu_t)+1);
            uu_pack_v1(&su, (U8*)dptr);
            dptr[sizeof(uu_t)] = '\0';
            SvCUR_set(out, sizeof(uu_t));
            (void)SvPOK_only(out);
            if (SvTYPE(out) == SVt_PVCV)
                CvAUTOLOAD_off(out);
            RETVAL = 0;
        }
#line 972 "lib/UUID.c"
	TARGi((IV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_time); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_time)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "in");
    {
	SV *	in = ST(0)
;
#line 587 "lib/UUID.xs"
        dUCXT;
#line 991 "lib/UUID.c"
	NV	RETVAL;
	dXSTARG;
#line 589 "lib/UUID.xs"
        struct_uu_t     su;
        char            *str;
        STRLEN          len;
#line 998 "lib/UUID.c"
#line 593 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        RETVAL = 0;
        if (SvPOK(in)) {
            str = SvPV(in, len);
            if (len == sizeof(uu_t)) {
                uu_pack_unpack((U8*)str, &su);
                RETVAL = uu_time(&su);
            }
        }
#line 1009 "lib/UUID.c"
	TARGn((NV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "in");
    {
	SV *	in = ST(0)
;
#line 610 "lib/UUID.xs"
        dUCXT;
#line 1028 "lib/UUID.c"
	IV	RETVAL;
	dXSTARG;
#line 612 "lib/UUID.xs"
        struct_uu_t     su;
        char            *str;
        STRLEN          len;
#line 1035 "lib/UUID.c"
#line 616 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        UU_ALIAS_VERSION(in, su, str, len);
#line 1039 "lib/UUID.c"
	TARGi((IV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_unparse); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_unparse)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "in, out");
    {
	SV *	in = ST(0)
;
	SV *	out = ST(1)
;
#line 627 "lib/UUID.xs"
        dUCXT;
#line 1060 "lib/UUID.c"
#line 629 "lib/UUID.xs"
        struct_uu_t     su;
        char            *dptr = NULL;
#line 1064 "lib/UUID.c"
#line 632 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        UU_ALIAS_UNPARSE_LOWER(in, out, su, dptr);
#line 1068 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_unparse_lower); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_unparse_lower)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "in, out");
    {
	SV *	in = ST(0)
;
	SV *	out = ST(1)
;
#line 641 "lib/UUID.xs"
        dUCXT;
#line 1087 "lib/UUID.c"
#line 643 "lib/UUID.xs"
        struct_uu_t     su;
        char            *dptr = NULL;
#line 1091 "lib/UUID.c"
#line 646 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        UU_ALIAS_UNPARSE_LOWER(in, out, su, dptr);
#line 1095 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_unparse_upper); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_unparse_upper)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "in, out");
    {
	SV *	in = ST(0)
;
	SV *	out = ST(1)
;
#line 655 "lib/UUID.xs"
        dUCXT;
#line 1114 "lib/UUID.c"
#line 657 "lib/UUID.xs"
        struct_uu_t     su;
        char            *dptr = NULL;
#line 1118 "lib/UUID.c"
#line 660 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        UU_ALIAS_UNPARSE_UPPER(in, out, su, dptr);
#line 1122 "lib/UUID.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_UUID_uuid); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_uuid)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 667 "lib/UUID.xs"
        dUCXT;
#line 1137 "lib/UUID.c"
	SV *	RETVAL;
#line 669 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 1142 "lib/UUID.c"
#line 672 "lib/UUID.xs"
        UU_ALIAS_UUID4(su, dptr);
#line 1145 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_uuid0); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_uuid0)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 680 "lib/UUID.xs"
        dUCXT;
#line 1162 "lib/UUID.c"
	SV *	RETVAL;
#line 682 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 1167 "lib/UUID.c"
#line 685 "lib/UUID.xs"
        UU_ALIAS_UUID0(su, dptr);
#line 1170 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_uuid1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_uuid1)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 693 "lib/UUID.xs"
        dUCXT;
#line 1187 "lib/UUID.c"
	SV *	RETVAL;
#line 695 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 1192 "lib/UUID.c"
#line 698 "lib/UUID.xs"
        UU_ALIAS_UUID1(su, dptr);
#line 1195 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_uuid3); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_uuid3)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "namespace, name");
    {
	SV *	namespace = ST(0)
;
	SV *	name = ST(1)
;
#line 708 "lib/UUID.xs"
        dUCXT;
#line 1216 "lib/UUID.c"
	SV *	RETVAL;
#line 710 "lib/UUID.xs"
        char            *dptr, *sptr;
        STRLEN          dlen, slen;
        struct_uu_t     su;
#line 1222 "lib/UUID.c"
#line 714 "lib/UUID.xs"
        SvUPGRADE(namespace, SVt_PV);
        SvUPGRADE(name,      SVt_PV);
        sptr = SvPV(namespace, slen);
        dptr = SvPV(name,      dlen);

        if (slen == 36 && !uu_parse(sptr, &su)) {
            /* uuid string */
            UU_ALIAS_UUID3(su, dptr);
        }
        else if (slen == 16) {
            /* assume binary uuid */
            uu_pack_unpack((unsigned char*)sptr, &su);
            UU_ALIAS_UUID3(su, dptr);
        }
        else if (slen > 0  /* ibcmp first appears in v5.7.3 */
            && ( (slen == 3 && !ibcmp(sptr, "dns",  (I32)slen) && CopyD(&UU_namespace_dns,  &su, 1, struct_uu_t))
              || (slen == 3 && !ibcmp(sptr, "url",  (I32)slen) && CopyD(&UU_namespace_url,  &su, 1, struct_uu_t))
              || (slen == 3 && !ibcmp(sptr, "oid",  (I32)slen) && CopyD(&UU_namespace_oid,  &su, 1, struct_uu_t))
              || (slen == 4 && !ibcmp(sptr, "x500", (I32)slen) && CopyD(&UU_namespace_x500, &su, 1, struct_uu_t))
            )
        ) {
            UU_ALIAS_UUID3(su, dptr);
        }
        else {  /* slen == 0 ; assume url type */
            CopyD(&UU_namespace_url, &su, 1, struct_uu_t);
            UU_ALIAS_UUID3(su, dptr);
        }
#line 1251 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_uuid4); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_uuid4)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 748 "lib/UUID.xs"
        dUCXT;
#line 1268 "lib/UUID.c"
	SV *	RETVAL;
#line 750 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 1273 "lib/UUID.c"
#line 753 "lib/UUID.xs"
        UU_ALIAS_UUID4(su, dptr);
#line 1276 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_uuid5); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_uuid5)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "namespace, name");
    {
	SV *	namespace = ST(0)
;
	SV *	name = ST(1)
;
#line 763 "lib/UUID.xs"
        dUCXT;
#line 1297 "lib/UUID.c"
	SV *	RETVAL;
#line 765 "lib/UUID.xs"
        char            *dptr, *sptr;
        STRLEN          dlen, slen;
        struct_uu_t     su;
#line 1303 "lib/UUID.c"
#line 769 "lib/UUID.xs"
        SvUPGRADE(namespace, SVt_PV);
        SvUPGRADE(name,      SVt_PV);
        sptr = SvPV(namespace, slen);
        dptr = SvPV(name,      dlen);

        if (slen == 36 && !uu_parse(sptr, &su)) {
            /* uuid string */
            UU_ALIAS_UUID5(su, dptr);
        }
        else if (slen == 16) {
            /* assume binary uuid */
            uu_pack_unpack((unsigned char*)sptr, &su);
            UU_ALIAS_UUID5(su, dptr);
        }
        else if (slen > 0  /* ibcmp first appears in v5.7.3 */
            && ( (slen == 3 && !ibcmp(sptr, "dns",  (I32)slen) && CopyD(&UU_namespace_dns,  &su, 1, struct_uu_t))
              || (slen == 3 && !ibcmp(sptr, "url",  (I32)slen) && CopyD(&UU_namespace_url,  &su, 1, struct_uu_t))
              || (slen == 3 && !ibcmp(sptr, "oid",  (I32)slen) && CopyD(&UU_namespace_oid,  &su, 1, struct_uu_t))
              || (slen == 4 && !ibcmp(sptr, "x500", (I32)slen) && CopyD(&UU_namespace_x500, &su, 1, struct_uu_t))
            )
        ) {
            UU_ALIAS_UUID5(su, dptr);
        }
        else {  /* slen == 0 ; assume url type */
            CopyD(&UU_namespace_url, &su, 1, struct_uu_t);
            UU_ALIAS_UUID5(su, dptr);
        }
#line 1332 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_uuid6); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_uuid6)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 803 "lib/UUID.xs"
        dUCXT;
#line 1349 "lib/UUID.c"
	SV *	RETVAL;
#line 805 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 1354 "lib/UUID.c"
#line 808 "lib/UUID.xs"
        UU_ALIAS_UUID6(su, dptr);
#line 1357 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_uuid7); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_uuid7)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 816 "lib/UUID.xs"
        dUCXT;
#line 1374 "lib/UUID.c"
	SV *	RETVAL;
#line 818 "lib/UUID.xs"
        char            *dptr = NULL;
        struct_uu_t     su;
#line 1379 "lib/UUID.c"
#line 821 "lib/UUID.xs"
        UU_ALIAS_UUID7(su, dptr);
#line 1382 "lib/UUID.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_variant); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_variant)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "in");
    {
	SV *	in = ST(0)
;
#line 830 "lib/UUID.xs"
        dUCXT;
#line 1401 "lib/UUID.c"
	UV	RETVAL;
	dXSTARG;
#line 832 "lib/UUID.xs"
        struct_uu_t     su;
        char            *str;
        STRLEN          len;
#line 1408 "lib/UUID.c"
#line 836 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        RETVAL = 0;
        if (SvPOK(in)) {
            str = SvPV(in, len);
            if (len == sizeof(uu_t)) {
                uu_pack_unpack((unsigned char*)str, &su);
                RETVAL = uu_variant(&su);
            }
        }
#line 1419 "lib/UUID.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_UUID_version); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID_version)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "in");
    {
	SV *	in = ST(0)
;
#line 853 "lib/UUID.xs"
        dUCXT;
#line 1438 "lib/UUID.c"
	IV	RETVAL;
	dXSTARG;
#line 855 "lib/UUID.xs"
        struct_uu_t     su;
        char            *str;
        STRLEN          len;
#line 1445 "lib/UUID.c"
#line 859 "lib/UUID.xs"
        (void)my_cxtp; /* silence warning */
        UU_ALIAS_VERSION(in, su, str, len);
#line 1449 "lib/UUID.c"
	TARGi((IV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}

#ifdef ONLY_FOR_DEV
#define XSubPPtmpAAAA 1


XS_EUPXS(XS_UUID__dump_struct); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_UUID__dump_struct)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 870 "lib/UUID.xs"
        dUCXT;
#line 1471 "lib/UUID.c"
#line 872 "lib/UUID.xs"
        my_cxt_t     *cxt  = my_cxtp;
        shared_mem_t *smem = cxt->shared;
#line 1475 "lib/UUID.c"
#line 875 "lib/UUID.xs"
        UV o = PTR2UV(&smem->LOCK);
        warn("============== shared_mem_t ==============\n");

        warn("LOCK .................. 0x%p %" UVuf "\n", &smem->LOCK               , PTR2UV(&smem->LOCK              ) - o);
        warn("__pad0 ................ 0x%p %" UVuf "\n", &smem->__pad0             , PTR2UV(&smem->__pad0            ) - o);
        UV len0 = sizeof(smem->LOCK) + sizeof(smem->__pad0);
        UV pages0 = len0 / 64; if (len0 % 64) ++pages0;
        warn("---- %" UVuf " bytes ; %" UVuf " * 64 = %" UVuf " bytes ----\n", len0, pages0, pages0*64);

        warn("clock_last ............ 0x%p %" UVuf "\n", &smem->clock_last         , PTR2UV(&smem->clock_last        ) - o);
        warn("  clock_last.tv_sec ... 0x%p %" UVuf "\n", &smem->clock_last.tv_sec  , PTR2UV(&smem->clock_last.tv_sec ) - o);
        warn("  clock_last.tv_usec .. 0x%p %" UVuf "\n", &smem->clock_last.tv_usec , PTR2UV(&smem->clock_last.tv_usec) - o);
        warn("clock_prev_reg ........ 0x%p %" UVuf "\n", &smem->clock_prev_reg     , PTR2UV(&smem->clock_prev_reg    ) - o);
        warn("clock_defer_100ns ..... 0x%p %" UVuf "\n", &smem->clock_defer_100ns  , PTR2UV(&smem->clock_defer_100ns ) - o);
        warn("clock_adj ............. 0x%p %" UVuf "\n", &smem->clock_adj          , PTR2UV(&smem->clock_adj         ) - o);
        warn("clock_seq ............. 0x%p %" UVuf "\n", &smem->clock_seq          , PTR2UV(&smem->clock_seq         ) - o);
        warn("__pad1 ................ 0x%p %" UVuf "\n", &smem->__pad1             , PTR2UV(&smem->__pad1            ) - o);
        UV len1 = sizeof(smem->clock_last) + sizeof(smem->clock_prev_reg) + sizeof(smem->clock_defer_100ns)
            + sizeof(smem->clock_adj) + sizeof(smem->clock_seq) + sizeof(smem->__pad1);
        UV pages1 = len1 / 64; if (len1 % 64) ++pages1;
        warn("---- %" UVuf " bytes ; %" UVuf " * 64 = %" UVuf " bytes ----\n", len1, pages1, pages1*64);

        warn("gen_epoch ............. 0x%p %" UVuf "\n", &smem->gen_epoch          , PTR2UV(&smem->gen_epoch         ) - o);
        warn("gen_node .............. 0x%p %" UVuf "\n", &smem->gen_node           , PTR2UV(&smem->gen_node          ) - o);
        warn("gen_has_real_node ..... 0x%p %" UVuf "\n", &smem->gen_has_real_node  , PTR2UV(&smem->gen_has_real_node ) - o);
        warn("gen_real_node ......... 0x%p %" UVuf "\n", &smem->gen_real_node      , PTR2UV(&smem->gen_real_node     ) - o);
        warn("gen_use_unique ........ 0x%p %" UVuf "\n", &smem->gen_use_unique     , PTR2UV(&smem->gen_use_unique    ) - o);
        warn("__pad2 ................ 0x%p %" UVuf "\n", &smem->__pad2             , PTR2UV(&smem->__pad2            ) - o);
        UV len2 = sizeof(smem->gen_epoch) + sizeof(smem->gen_node) + sizeof(smem->gen_has_real_node)
            + sizeof(smem->gen_real_node) + sizeof(smem->gen_use_unique) + sizeof(smem->__pad2);
        UV pages2 = len2 / 64; if (len2 % 64) ++pages2;
        warn("---- %" UVuf " bytes ; %" UVuf " * 64 = %" UVuf " bytes ----\n", len2, pages2, pages2*64);

        warn("cc .................... 0x%p %" UVuf "\n", &smem->cc                 , PTR2UV(&smem->cc                ) - o);
        warn("  cc.state ............ 0x%p %" UVuf "\n", &smem->cc.state           , PTR2UV(&smem->cc.state          ) - o);
        warn("  cc.buf .............. 0x%p %" UVuf "\n", &smem->cc.buf             , PTR2UV(&smem->cc.buf            ) - o);
        warn("  cc.have ............. 0x%p %" UVuf "\n", &smem->cc.have            , PTR2UV(&smem->cc.have           ) - o);
        warn("  cc.__align .......... 0x%p %" UVuf "\n", &smem->cc.__align         , PTR2UV(&smem->cc.__align        ) - o);
        warn("xo_s .................. 0x%p %" UVuf "\n", &smem->xo_s               , PTR2UV(&smem->xo_s              ) - o);
        warn("sm_x .................. 0x%p %" UVuf "\n", &smem->sm_x               , PTR2UV(&smem->sm_x              ) - o);
        warn("__pad3 ................ 0x%p %" UVuf "\n", &smem->__pad3             , PTR2UV(&smem->__pad3            ) - o);
        UV len3 = sizeof(smem->cc) + sizeof(smem->xo_s) + sizeof(smem->sm_x) + sizeof(smem->__pad3);
        UV pages3 = len3 / 64; if (len3 % 64) ++pages3;
        warn("---- %" UVuf " bytes ; %" UVuf " * 64 = %" UVuf " bytes ----\n", len3, pages3, pages3*64);

        warn("clock_persist ......... 0x%p %" UVuf "\n", &smem->clock_persist      , PTR2UV(&smem->clock_persist     ) - o);
        warn("  clock_persist.len ... 0x%p %" UVuf "\n", &smem->clock_persist.len  , PTR2UV(&smem->clock_persist.len ) - o);
        warn("  clock_persist.path .. 0x%p %" UVuf "\n", &smem->clock_persist.path , PTR2UV(&smem->clock_persist.path) - o);
        UV len4 = sizeof(smem->clock_persist);
        UV pages4 = len4 / 64; if (len4 % 64) ++pages4;
        warn("---- %" UVuf " bytes ; %" UVuf " * 64 = %" UVuf " bytes ----\n", len4, pages4, pages4*64);

        warn("shared_mem_t size : %lu\n\n", sizeof(shared_mem_t));

        warn("============== my_cxt_t ==============\n");
        o = PTR2UV(&cxt->shared);
        warn("shared ................ 0x%p %" UVuf "\n", &cxt->shared             , PTR2UV(&cxt->shared            ) - o);
        warn("shared_len ............ 0x%p %" UVuf "\n", &cxt->shared_len         , PTR2UV(&cxt->shared_len        ) - o);
        warn("clock_state_f ......... 0x%p %" UVuf "\n", &cxt->clock_state_f      , PTR2UV(&cxt->clock_state_f     ) - o);
        warn("clock_state_fd ........ 0x%p %" UVuf "\n", &cxt->clock_state_fd     , PTR2UV(&cxt->clock_state_fd    ) - o);
        warn("__pad5 ................ 0x%p %" UVuf "\n", &cxt->__pad5             , PTR2UV(&cxt->__pad5            ) - o);
        UV len5 = sizeof(cxt->shared) + sizeof(cxt->shared_len) + sizeof(cxt->clock_state_f)
            + sizeof(cxt->clock_state_fd) + sizeof(cxt->__pad5);
        UV pages5 = len5 / 64; if (len5 % 64) ++pages5;
        warn("---- %" UVuf " bytes ; %" UVuf " * 64 = %" UVuf " bytes ----\n", len5, pages5, pages5*64);

        warn("clock_persist ......... 0x%p %" UVuf "\n", &cxt->clock_persist      , PTR2UV(&cxt->clock_persist     ) - o);
        warn("  clock_persist.len ... 0x%p %" UVuf "\n", &cxt->clock_persist.len  , PTR2UV(&cxt->clock_persist.len ) - o);
        warn("  clock_persist.path .. 0x%p %" UVuf "\n", &cxt->clock_persist.path , PTR2UV(&cxt->clock_persist.path) - o);
        UV len6 = sizeof(cxt->clock_persist);
        UV pages6 = len6 / 64; if (len6 % 64) ++pages6;
        warn("---- %" UVuf " bytes ; %" UVuf " * 64 = %" UVuf " bytes ----\n", len6, pages6, pages6*64);

        warn("my_cxt_t size : %lu\n\n", sizeof(my_cxt_t));
        warn("uu_mutex: %lu\n", sizeof(uu_mutex));
#line 1552 "lib/UUID.c"
	PUTBACK;
	return;
    }
}

#endif
#ifdef __cplusplus
extern "C" {
#endif
XS_EXTERNAL(boot_UUID); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_UUID)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        (void)newXSproto_portable("UUID::_hide_always", XS_UUID__hide_always, file, "");
        (void)newXSproto_portable("UUID::_hide_mac", XS_UUID__hide_mac, file, "");
        (void)newXSproto_portable("UUID::_persist", XS_UUID__persist, file, "@");
        (void)newXSproto_portable("UUID::_realnode", XS_UUID__realnode, file, "");
        (void)newXSproto_portable("UUID::_defer", XS_UUID__defer, file, "@");
        (void)newXSproto_portable("UUID::clear", XS_UUID_clear, file, "$");
        (void)newXSproto_portable("UUID::compare", XS_UUID_compare, file, "$$");
        (void)newXSproto_portable("UUID::copy", XS_UUID_copy, file, "$$");
        (void)newXSproto_portable("UUID::generate", XS_UUID_generate, file, "$");
        (void)newXSproto_portable("UUID::generate_random", XS_UUID_generate_random, file, "$");
        (void)newXSproto_portable("UUID::generate_time", XS_UUID_generate_time, file, "$");
        (void)newXSproto_portable("UUID::generate_v0", XS_UUID_generate_v0, file, "$");
        (void)newXSproto_portable("UUID::generate_v1", XS_UUID_generate_v1, file, "$");
        (void)newXSproto_portable("UUID::generate_v3", XS_UUID_generate_v3, file, "$$$");
        (void)newXSproto_portable("UUID::generate_v4", XS_UUID_generate_v4, file, "$");
        (void)newXSproto_portable("UUID::generate_v5", XS_UUID_generate_v5, file, "$$$");
        (void)newXSproto_portable("UUID::generate_v6", XS_UUID_generate_v6, file, "$");
        (void)newXSproto_portable("UUID::generate_v7", XS_UUID_generate_v7, file, "$");
        (void)newXSproto_portable("UUID::is_null", XS_UUID_is_null, file, "$");
        (void)newXSproto_portable("UUID::parse", XS_UUID_parse, file, "$$");
        (void)newXSproto_portable("UUID::time", XS_UUID_time, file, "$");
        (void)newXSproto_portable("UUID::type", XS_UUID_type, file, "$");
        (void)newXSproto_portable("UUID::unparse", XS_UUID_unparse, file, "$$");
        (void)newXSproto_portable("UUID::unparse_lower", XS_UUID_unparse_lower, file, "$$");
        (void)newXSproto_portable("UUID::unparse_upper", XS_UUID_unparse_upper, file, "$$");
        (void)newXSproto_portable("UUID::uuid", XS_UUID_uuid, file, "");
        (void)newXSproto_portable("UUID::uuid0", XS_UUID_uuid0, file, "");
        (void)newXSproto_portable("UUID::uuid1", XS_UUID_uuid1, file, "");
        (void)newXSproto_portable("UUID::uuid3", XS_UUID_uuid3, file, "$$");
        (void)newXSproto_portable("UUID::uuid4", XS_UUID_uuid4, file, "");
        (void)newXSproto_portable("UUID::uuid5", XS_UUID_uuid5, file, "$$");
        (void)newXSproto_portable("UUID::uuid6", XS_UUID_uuid6, file, "");
        (void)newXSproto_portable("UUID::uuid7", XS_UUID_uuid7, file, "");
        (void)newXSproto_portable("UUID::variant", XS_UUID_variant, file, "$");
        (void)newXSproto_portable("UUID::version", XS_UUID_version, file, "$");
#if XSubPPtmpAAAA
        (void)newXSproto_portable("UUID::_dump_struct", XS_UUID__dump_struct, file, "");
#endif

    /* Initialisation Section */

#line 152 "lib/UUID.xs"
    UCXT_INIT;
    smem_init(aUCXT);
    UMTX_INIT;
    UMTX_LOCK {

    /* order important */
    uu_gettime_init(aUCXT);
    uu_clock_init(aUCXT);
    uu_chacha_srand(aUCXT);  /* must be before gen_init, but after clock_init */
    uu_gen_init(aUCXT);

    uu_chacha_rand16(aUCXT, &SMEM->clock_seq);

    } UMTX_UNLOCK

#if XSubPPtmpAAAA
#endif
#line 1646 "lib/UUID.c"

    /* End of Initialisation Section */

#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

#ifdef __cplusplus
}
#endif
